apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "config-controller.labels" . | nindent 4 }}
  name: {{ include "config-controller.fullname" . }}-{{ .Release.Namespace }}
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "create", "delete"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list"]
  - apiGroups: [""]  # coreAPI group
    resources: ["pods"]
    verbs: ["get", "watch", "list", "delete", "patch"]
