apiVersion: v2
name: config-controller
version: "2.2.0"
description: A manager for (stateful) intens applications
type: application

home: https://gitlab.semafor.ch/semafor/config-controller
sources:
  - https://gitlab.semafor.ch/semafor/config-controller



appVersion: "2.3.0"
