apiVersion: v2
name: config-controller
version: "2.4.1"
description: A manager for (stateful) intens applications
type: application

home: https://github.com/SEMAFORInformatik/config-controller
sources:
  - https://github.com/SEMAFORInformatik/config-controller



appVersion: "2.4.1"
